export const rooms = {
  data: [
    {
      key: "001",
      name: "1st Floor NW Room",
      capacity: 10,
      occupied: 0,
      type: "HOME",
    },
    {
      key: "002",
      name: "1st Floor SW Room",
      capacity: 6,
      occupied: 0,
      type: "HOME",
    },
    {
      key: "003",
      name: "1st Floor NE Room (Preeti)",
      capacity: 6,
      occupied: 0,
      type: "HOME",
    },
    {
      key: "004",
      name: "1st Floor Master Room",
      capacity: 6,
      occupied: 0,
      type: "HOME",
    },
    {
      key: "005",
      name: "Ground Floor NW Room",
      capacity: 6,
      occupied: 0,
      type: "HOME",
    },
    {
      key: "006",
      name: "Ground Floor SW Room (Ankit)",
      capacity: 4,
      occupied: 0,
      type: "HOME",
    },
    {
      key: "301",
      name: "Room Number 301",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "302",
      name: "Room Number 302",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "303",
      name: "Room Number 303",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "305",
      name: "Room Number 305",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "306",
      name: "Room Number 306",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "307",
      name: "Room Number 307",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "311",
      name: "Room Number 311",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "312",
      name: "Room Number 312",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "313",
      name: "Room Number 313",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "314",
      name: "Room Number 314",
      type: "HOTEL",
      capacity: 4,
      occupied: 0,
    },
    {
      key: "315",
      name: "Room Number 315",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "316",
      name: "Room Number 316",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "317",
      name: "Room Number 317",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "318",
      name: "Room Number 318",
      type: "HOTEL",
      capacity: 6,
      occupied: 0,
    },
    {
      key: "319",
      name: "Room Number 319",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "320",
      name: "Room Number 320",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "321",
      name: "Room Number 321",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "322",
      name: "Room Number 322",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
  ],
};
