export const rooms = {
  data: [
    {
      key: 1,
      name: "1st Floor NW Room",
      capacity: 5,
      occupied: 0,
      type: "HOME",
    },
    {
      key: 2,
      name: "1st Floor SW Room",
      capacity: 5,
      occupied: 0,
      type: "HOME",
    },
    {
      key: 3,
      name: "1st Floor NE Room",
      capacity: 3,
      occupied: 0,
      type: "HOME",
    },
    {
      key: 4,
      name: "Ground Floor NW Room",
      capacity: 5,
      occupied: 0,
      type: "HOME",
    },
    {
      key: 1,
      name: "Ground Floor SW Room",
      capacity: 2,
      occupied: 0,
      type: "HOME",
    },
    {
      key: "1",
      name: "Room Number 1",
      type: "HOTEL",
      capacity: 4,
      occupied: 0,
    },
    {
      key: "2",
      name: "Room Number 2",
      type: "HOTEL",
      capacity: 4,
      occupied: 0,
    },
    {
      key: "3",
      name: "Room Number 3",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "4",
      name: "Room Number 4",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "5",
      name: "Room Number 5",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "6",
      name: "Room Number 6",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "7",
      name: "Room Number 7",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "8",
      name: "Room Number 8",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "9",
      name: "Room Number 9",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "10",
      name: "Room Number 10",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "11",
      name: "Room Number 11",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "12",
      name: "Room Number 12",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "13",
      name: "Room Number 13",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "14",
      name: "Room Number 14",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "15",
      name: "Room Number 15",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "16",
      name: "Room Number 16",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "17",
      name: "Room Number 17",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
    {
      key: "18",
      name: "Room Number 18",
      type: "HOTEL",
      capacity: 2,
      occupied: 0,
    },
  ],
};
